master:
  image: docker-registry.newsweaver.lan/spark-master:1.4.1
  hostname: master
  expose: ['7077', '8090']
  volumes:
  - ./target/scala-2.10:/opt/shared/sparkapps
  - ./src/integrationtest/spark:/opt/shared/spark
csgossipnode:
  image: docker-registry.newsweaver.lan/cassandra-spark:spark-1.4.1
  hostname: csgossipnode
  expose: ['7077','7000','7199','9042', '9160']
  links:
    - master
  environment:
    SPARK_MASTER_IP: "master"
csnode:
  image: docker-registry.newsweaver.lan/cassandra-spark:spark-1.4.1
  expose: ['7077','7000','7199','9042', '9160']
  links:
    - master
    - csgossipnode
  environment:
    SPARK_MASTER_IP: "master"
    CASSANDRA_SEED_IP: "csgossipnode"
